[book]
title = "Język Programowania Rust"
authors = ["Steve Klabnik", "Carol Nichols", "Z udziałem Społeczności Rusta"]
language = "pl"

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/beling/book-pl"
